config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'articles#index'
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]

  resources :articles do
    resources :comments
    resources :votes, only: [:create, :destroy]
  end
  resources :tags
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_attached_file :image
  has_many :votes, dependent: :destroy
  belongs_to :user
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 500 }
  validates :image, presence: true
  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  delegate :username, to: :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :articles
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.save
        redirect_to root_url
    end


    private
        def article_params
            params.require(article).permit(:title, :body, :image)
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  def index
    @articles = Article.all
    @articles = Article.includes(:votes).order('vote_count DESC').limit(5)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article '#{@article.title}' Deleted"
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tag = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "Tag #{@tag.name} deleted!"
    redirect_to articles_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  before_action :check_authorization, only: %i[edit update]
  before_action :set_user
  def show; end

  def edit
    if @user.edit(user_params)
      redirect_to @user
    else
      flash.now[:alert] = 'Somthing went wrong, Please try again'
      render :edit
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:alert] = 'Somthing went wrong, Please try again'
      render :edit
    end
  end

  private

  def check_authorization
    redirect_to root_url unless current_user.id == params[:id].to_i
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    v = current_user.votes.new(article_id: params[:article_id])
    return unless v.save

    Article.find(params[:article_id]).increment!(:vote_count)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    v = Vote.find_by(user_id: current_user.id, article_id: params[:article_id])
    return unless v

    Article.find(params[:article_id]).decrement!(:vote_count) if v.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def vote_button(article)
    return if current_user.nil?

    if article.votes.map(&:user_id).any?(current_user.id)
      link_to 'Remove Vote', article_vote_path(article), method: :delete, class: 'btn btn-danger'
    else
      link_to 'Vote', article_votes_path(article), method: :post, class: 'btn btn-primary'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_comment.html.erb
    <h4>Comment by <%= comment.author_name %></h4>
    <p class="comment"><%= comment.body %></p>
    <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-8 col-md-offset-3">
    <%= form_for(@article, html: {multipart: true}) do |f| %>
        <ul>
        <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
        </ul>
        <p>
          <%= f.label :tag_list, "Categories" %><br />
          <%= f.text_field :tag_list,  class:"form-control" %>
        </p>
     
      <p>
        <%= f.label :image, "Attach an Image" %><br />
        <%= f.file_field :image %>
      </p>
      
        <p>
          <%= f.label :title %><br />
          <%= f.text_field :title,  class:"form-control" %>
        </p>
        <p>
          <%= f.label :body %><br />
          <%= f.text_area :body,  class:"form-control" %>
        </p>
        <p>
          <%= f.submit 'Submit', class:"btn btn-primary" %>
        </p>

      <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<div class="row" style="margin-top: -20px;">
  <% i = 0 %>
    <% @articles.in_groups_of(1, false) do |group| %>
      <% group.each do |article| %>
        <% if i.zero? %>
          <div class="col-sm-12">
        <div class="card" >
          <img class="card-img-top"style=" width: 100%; height: 425px;" src="<%= article.image %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          </div>
        </div>
      </div>
      <% else %>
          <div class="col-sm-3">
          <div class="card" >
              <img class="card-img-top"style=" width: 100%; height: 263px;" src="<%= article.image %>" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% i = i+1 %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-8 col-md-offset-3">
    <h1><%= @article.title %></h1>
    <p>
      Categories:
      <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </p>

    <img style=" width: 70%; " src=<%=@article.image%>>
    <p><%= @article.body %></p>
    <p class="btn btn-primary">Has <%= pluralize(@article.vote_count, 'vote')%></p>
    <% if user_signed_in? %>
    <div class="d-flex pl-1 pb-1">
        <span class="mr-3">
          <%= vote_button  @article%>
        </span>
    </div>
    <%end%>
    <h3>Comments (<%= @article.comments.size %>)</h3>

    <%= render partial: 'articles/comment', collection: @article.comments %>
    <%= render partial: 'comments/form' %>
<br>



      <br>
    <%= link_to "<< Back to Articles List", articles_path, class:"btn btn-primary" %>
    <% if @article.user ==  current_user%>
      <%= link_to "edit", edit_article_path(@article), class:"btn btn-primary" %>
      <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}, class:"btn btn-danger"%>
    <%end%>
  </div>
</div>

app/views/comments/_form.html.erb
    <h3>Post a Comment</h3>

    <%= form_for [ @article, @comment ] do |f| %>
      

      <div class="field">
        <%= f.label :author_name, "Your Name" %><br/>
        <%= f.text_field :author_name ,  class:"form-control" %>
      </div>

      <div class="field">
        <%= f.label :body %><br/>
        <%= f.text_area :body,  class:"form-control"  %>
      </div>
<br>
      <div class="field">
        <%= f.submit 'Submit', class:"btn btn-primary" %>
      </div>
    <% end %>

app/views/posts/_post.html.erb
<%= item.username%>
<%= item.title%>

app/views/posts/new.html.erb
<h1>New post<h1>

<%= form_for @post do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%>

    <%= f.label :body%>
    <%= f.text_area :body%>

    <%= f.submit "Publish"%>

<%end%>

app/views/posts/show.html.erb
<h1>Life Style</h1>

<% @posts.each do |item| %>
  <%= render @posts%>
<% end %>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tag.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<div class="row" style="margin-top: -20px;">
  <% i = 0 %>
    <% @tag.articles.in_groups_of(1, false) do |group| %>
      <% group.each do |article| %>
      <% if i.zero? %>
      <div class="col-12 col-md-6">
        <div class="row no-gutters">
          <div class="col-12 col-md-6 bg-article" style="height: 316px;background: url(<%= article.image  %>)">
          </div>
          <div class="col-12 col-md-6">
            <h2 class="cat-show-tile"><%= article.title%></h2>
            <span class="article-title font-weight-bold"><%= article.body.first(120)%> </span><br/>
            <%= link_to "Read more", article_path(article), class:"btn btn-primary" %>
          </div>
        </div>
      </div>
      <% else %>
        <div class="col-12 col-md-6">
          <div class="row no-gutters">
            <div class="col-12 col-md-6">
              <h2 class="cat-show-tile"><%= article.title%></h2>
              <span class="article-title font-weight-bold"><%= article.body.first(120)%> </span><br/>
              <%= link_to "Read more", article_path(article), class:"btn btn-primary" %>
            </div>
            <div class="col-12 col-md-6 bg-article" style="height: 316px;background: url(<%= article.image  %>)">
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
    <% i = i+1 %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for (@user) do |f| %>
    <%= f.label :email %><br />
    <%= f.email_field :email%>
  
    <%= f.submit "Save" %> 
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%= @user.email%> </h1>
<%= link_to "Edit", edit_user_path(@user) %>